env: standard
runtime: nodejs16

handlers:
  - url: /static
    static_dir: dist/static
  - url: /(.*\.(json|ico|js|css))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js|css)$
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
